version: "3.8"

services:
  backend:
    env_file: .env
    build: .
    tty: true
    volumes:
      - ./src:/follow.bot/src
      - ./resources:/follow.bot/resources

  database:
    env_file: .env
    image: postgres:15.1-alpine
    expose:
      - 5432
    volumes:
      - database_data:/var/lib/postgresql/data

  redis:
    env_file: .env
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    volumes:
      - cache:/data

volumes:
  database_data:
  cache:
    driver: local